2021-04-06 21:01:30,671 ERROR: Exception on /socketo [GET] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/socketo/routes.py", line 14, in S_S
    return render_template('socketo/SIO.html', **values)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: socketo/SIO.html
2021-04-06 21:01:34,925 ERROR: Exception on /socketo [GET] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/socketo/routes.py", line 14, in S_S
    return render_template('socketo/SIO.html', **values)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: socketo/SIO.html
2021-04-06 21:02:09,860 ERROR: Exception on /socketo [GET] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/socketo/routes.py", line 14, in S_S
    return render_template('socketo/SIO.html', **values)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: socketo/SIO.html
2021-04-06 21:03:05,370 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:03:22,712 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:09:23,328 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:09:51,598 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:12:52,104 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:13:25,577 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:14:07,994 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:14:50,435 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:19:24,071 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:19:30,314 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:23:36,783 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:25:09,772 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:28:51,743 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:29:24,577 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:29:56,614 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 21:30:29,671 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-06 23:27:06,534 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-07 00:00:00,792 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-07 00:01:39,822 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-07 00:13:44,802 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
2021-04-07 00:13:52,905 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:86]
